### ISSUE TITLE
SJulia on OSX using issue

### ISSUE THREAD

**Issue by goedman** [jlapeyre/SJulia.jl#19]
Hi John,

Have you come across this problem? Earlier I did get SJulia to work on my system, but not since upgrading to Julia 0.5.0-rc3.

I installed mpmath both via pip and via conda

If you prefer, I could also create an issue on SJulia.

Thanks,
Rob
[SJulia_using_issues.txt](https://github.com/jlapeyre/SJulia.jl/files/453492/SJulia_using_issues.txt)

**Comment by jlapeyre** [comment]
Hi Rob,

I just made fixes and a pushed them. I run Tests() and all tests now pass with 0.5rc3. Unfortunately, some tests now fail for 0.4, and I don't have time to fix them at the moment.

Please let me know if you still have problems.

Thanks,
John

**Comment by goedman** [comment]
Hi John,

Back in business!!! Thanks a lot.

Regards,
Rob

**Comment by jlapeyre** [comment]
Great.
