### ISSUE TITLE
SJulia integer should be big?

### ISSUE THREAD

**Issue by Upabjojr** [jlapeyre/SJulia.jl#8]
I noticed this while writing the parser for the other issue.

Anyways:
```
julia> @ex SetJ(x, 1)
1

julia> x |> typeof
Int64
```
I think Mathematica uses big integers by default, isn't it?

**Comment by jlapeyre** [comment]
I'm not sure. They only present one type of Integer to the user. ByteCount[1] gives 16 on an old version of Mma, suggesting they are already not using a machine type. But, ByteCount[1.0] also gives 16, and 1.0 is supposed to be a "machine size" floating point number with 16 digits of precision. I guess Mma uses something efficient internally for small integers.

Making everything a big int sounds like a bad idea. I guess that some type of automatic promotion is best, but I have not thought about how to integrate this. In most  SJulia code, I have 0, 1, etc. This should be one(x), or SJuliaOne, etc.  One could also preserve the Julia model of requiring the user to manage promotion, but a symbolic language already gives up a lot of performance, so automatic promotion may be ok.

**Comment by jlapeyre** [comment]
... there are other potential incompatibilities. Mathematica allows complex numbers of mixed type. Julia does not.

**Comment by jlapeyre** [comment]
By the way, to assign Mxpr's to Julia variables you can also do this
```julia
julia> a = @ex x + 1
1 + x

julia> typeof(a)
SJulia.Mxpr{Plus}

julia> @ex m = x + 1
1 + x

julia> a = symval(:m)   # or this
1 + x
```

**Comment by jlapeyre** [comment]
Mathematica uses both machine integers and bigints. Timing `Range[10^6]`, gives the same time as Julia takes to create array of type Int: `collect(1:10^6)`.  Setting (in Mma) one of the values of the resulting `List` to a float, eg. 1.0, causes the storage to be copied to an array of something like `Any`. This copy takes the same time as it takes Julia to do `Any[i for i in 1:10^6]`. The copy takes 20 to 30 times longer than creating the initial array.  SJulia currently always uses arrays of type `Any`.  But, you can use Julia arrays for some things. Eg. create an array `sjulia > a = :( collect(1:10) )`. But, this array is seen as atomic to most SJulia functions.

In commit 5a774cd6f9c84f0574fa8a4fd4dd403d82553827, I added functions BigIntInput(True), and BigFloatInput(True) (or False) to dynamically reinterpret all input numbers as BigInts or BigFloats.

Then you can do things like  `2^10000` and get what you want.  I did not even try to run the entire test suite with this feature enabled. But, I added a few tests with it enabled.
